### ISSUE TITLE
Use XDG conventions for config folder

### ISSUE THREAD

**Issue by kwill** [albertodonato/sshoot#1]
**User story:** I am a regular GNU/Linux user. I look for configuration files I expect to find them in `~/.config` because this is where most of my modern libraries/tools store them.

**Steps to reproduce:**
* Create a profile in sshoot

**What should happen:**
* Profile is stored in `~/.config/sshoot/`

**What happens instead:**
* Profile is stored in `~/.sshoot/`

**Suggested solution:**
* Switch to `~/.config/sshoot/`
* (optionally) Fall back on `~/.sshoot/` iff `~/.config/sshoot/` doesn't exist and `~/.sshoot/` does exist
* (optionally) Use [xdg](https://pypi.python.org/pypi/xdg) or [any other app-folder library](https://pypi.python.org/pypi?:action=search&term=xdg) to generate the path.

**Workaround:**
* Always use `-C ~/.config/sshoot` option to force expected behaviour

**Comment by kwill** [comment]
**Alternate workaround:**

 * Create a symbolic link: `ln --symbolic --force ~/.config/sshoot ~/.sshoot`

**Comment by albertodonato** [comment]
Fixed in 1.3.0
