### ISSUE TITLE
Invalid profile config 'config' error when creating environment

### ISSUE THREAD

**Issue by gercograndia** [albertodonato/sshoot#10]
With a completely fresh install of `sshoot` (sshuttle is already there):

```bash
$ sshoot --version
sshoot 1.5.0

$ sshoot create -r my-server -HNd vpn1 10.0.0.0/8
Invalid profile config 'config's

$ sshoot list
   Name  Remote host  Subnets
-------------------------------
```

**Comment by gercograndia** [comment]
Btw, working with python 3.8.3 on macos.

**Comment by gercograndia** [comment]
Closed? 

Noticed you pushed some changes but not published it on pypi? Still version 1.5.0 there with the same problem.

I can imagine my previous remark "Btw, working with python 3.8.3 on macos." might have been a bit confusing.

I am working on macos 11.1 with python 3.8.3 but sshoot is *not* working (yet at least).

**Comment by albertodonato** [comment]
It's fixed in master (by the commit you mentioned).
I'll make a release with the fix soon.

**Comment by gercograndia** [comment]
Excellent, thanks a lot!
