### ISSUE TITLE
PyPI entry doesn't render correctly

### ISSUE THREAD

**Issue by kwill** [albertodonato/sshoot#2]
**Steps to reproduce:**
* Visit https://pypi.python.org/pypi/sshoot

**What should happen:**
* Page renders, badges are visible, formatting is correct

**What happens instead:**
* Page renders, but badges are not visible, formatting is not applied

**Comment by albertodonato** [comment]
This is related to https://github.com/pypa/warehouse/issues/869

**Comment by albertodonato** [comment]
Fixed in v1.4.0 by switching to reST format for readme
