### ISSUE TITLE
yaml.load deprecated warning/how about a new release

### ISSUE THREAD

**Issue by douglassd** [albertodonato/sshoot#6]
/usr/lib/python3.7/site-packages/sshoot/config.py:69: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(path.read_text()) or {}

System is Arch Linux, sshoot version is 1.4.1-1 from the AUR (https://aur.archlinux.org/packages/sshoot).

Above warning message began appearing with update to version 5.1-1 of python-yaml.

Looking at the latest code in master, you've already fixed this issue. How about a new release?

P.S. Thanks for making sshuttle easier to use

**Comment by albertodonato** [comment]
Fixed in 1.4.2.
